import type { 
  SpliceJoint, 
  DamageMarker, 
  SensorNode, 
  AlertLog, 
  MLMetrics, 
  ConveyorTelemetry,
  PurdueZoneStatus,
  CyberThreatEvent,
  PersonnelZoneTracker,
  LotoLockRecord
} from '../types/telemetry';

export const INITIAL_SPLICES: SpliceJoint[] = [
  {
    id: 1,
    label: 'Joint Splice #01 (Drive Discharge)',
    type: 'Steel Cord ST-5400 Multi-Step',
    locationMeter: 120,
    degradationPercent: 12.4,
    ruptureRiskPercent: 4.8,
    status: 'NOMINAL',
    dynamicStrainMicrostrain: 640,
    strainThreshold: 1150,
    cordPullOutMm: 1.1,
    maxAllowedPullOutMm: 12.0,
    temperatureC: 38.2,
    installedDate: '2025-11-14',
    lastInspected: '2026-08-28 09:30',
    confidenceScore: 0.98,
    anomalyNotes: 'Uniform vulcanization bond; normal flexure profile.',
  },
  {
    id: 2,
    label: 'Joint Splice #02 (Overland Run A)',
    type: 'Steel Cord ST-5400 Multi-Step',
    locationMeter: 750,
    degradationPercent: 18.1,
    ruptureRiskPercent: 6.2,
    status: 'NOMINAL',
    dynamicStrainMicrostrain: 690,
    strainThreshold: 1150,
    cordPullOutMm: 2.0,
    maxAllowedPullOutMm: 12.0,
    temperatureC: 34.5,
    installedDate: '2025-08-20',
    lastInspected: '2026-08-28 09:32',
    confidenceScore: 0.97,
    anomalyNotes: 'Stable telemetry. Minor rubber cover abrasive wear.',
  },
  {
    id: 3,
    label: 'Joint Splice #03 (Chute Impact Zone)',
    type: 'Steel Cord ST-5400 Heavy Reinforced',
    locationMeter: 1450,
    degradationPercent: 42.5,
    ruptureRiskPercent: 28.6,
    status: 'ADVISORY',
    dynamicStrainMicrostrain: 890,
    strainThreshold: 1150,
    cordPullOutMm: 4.8,
    maxAllowedPullOutMm: 12.0,
    temperatureC: 44.1,
    installedDate: '2025-04-10',
    lastInspected: '2026-09-01 06:15',
    confidenceScore: 0.94,
    anomalyNotes: 'Moderate dynamic impact stress recorded during primary crushing cycles.',
  },
  {
    id: 4,
    label: 'Joint Splice #04 (High-Tension Zone)',
    type: 'Steel Cord ST-5400 Multi-Step',
    locationMeter: 2180,
    degradationPercent: 86.4,
    ruptureRiskPercent: 92.1,
    status: 'CRITICAL',
    dynamicStrainMicrostrain: 1280,
    strainThreshold: 1150,
    cordPullOutMm: 14.8,
    maxAllowedPullOutMm: 12.0,
    temperatureC: 62.8,
    installedDate: '2024-11-02',
    lastInspected: '2026-09-01 18:45',
    confidenceScore: 0.99,
    anomalyNotes: 'CRITICAL: Severe core steel cord slippage (+14.8mm) detected. Micro-crack propagation in bonding rubber.',
  },
  {
    id: 5,
    label: 'Joint Splice #05 (Mid-Span Overland)',
    type: 'Steel Cord ST-5400 Multi-Step',
    locationMeter: 2900,
    degradationPercent: 22.0,
    ruptureRiskPercent: 7.9,
    status: 'NOMINAL',
    dynamicStrainMicrostrain: 670,
    strainThreshold: 1150,
    cordPullOutMm: 2.3,
    maxAllowedPullOutMm: 12.0,
    temperatureC: 33.9,
    installedDate: '2025-06-18',
    lastInspected: '2026-08-30 14:10',
    confidenceScore: 0.98,
    anomalyNotes: 'Nominal cord pitch and magnetic flux signature.',
  },
  {
    id: 6,
    label: 'Joint Splice #06 (Tail Station Take-up)',
    type: 'Steel Cord ST-5400 Reinforced',
    locationMeter: 3620,
    degradationPercent: 54.2,
    ruptureRiskPercent: 44.0,
    status: 'WARNING',
    dynamicStrainMicrostrain: 1040,
    strainThreshold: 1150,
    cordPullOutMm: 7.9,
    maxAllowedPullOutMm: 12.0,
    temperatureC: 48.6,
    installedDate: '2025-02-12',
    lastInspected: '2026-09-01 11:20',
    confidenceScore: 0.95,
    anomalyNotes: 'Elevated cyclic tension near gravity take-up pulley. Recommend scheduled re-splice in 72h.',
  },
  {
    id: 7,
    label: 'Joint Splice #07 (Return Strand West)',
    type: 'Steel Cord ST-5400 Multi-Step',
    locationMeter: 4180,
    degradationPercent: 19.5,
    ruptureRiskPercent: 6.8,
    status: 'NOMINAL',
    dynamicStrainMicrostrain: 590,
    strainThreshold: 1150,
    cordPullOutMm: 1.8,
    maxAllowedPullOutMm: 12.0,
    temperatureC: 31.4,
    installedDate: '2025-09-05',
    lastInspected: '2026-08-25 16:40',
    confidenceScore: 0.98,
    anomalyNotes: 'Clean return strand tracking with balanced edge tension.',
  },
  {
    id: 8,
    label: 'Joint Splice #08 (Return Drive Approach)',
    type: 'Steel Cord ST-5400 Multi-Step',
    locationMeter: 4680,
    degradationPercent: 26.8,
    ruptureRiskPercent: 11.2,
    status: 'NOMINAL',
    dynamicStrainMicrostrain: 650,
    strainThreshold: 1150,
    cordPullOutMm: 2.9,
    maxAllowedPullOutMm: 12.0,
    temperatureC: 35.8,
    installedDate: '2025-07-22',
    lastInspected: '2026-08-29 18:00',
    confidenceScore: 0.96,
    anomalyNotes: 'Normal transition dynamics into drive pulley snub.',
  },
];

export const INITIAL_ANOMALIES: DamageMarker[] = [
  {
    id: 'DM-104',
    type: 'STEEL_CORD_PULL_OUT',
    label: 'Splice #4 Cord Rupture Hazard',
    locationMeter: 2180,
    severity: 'CRITICAL',
    confidence: 0.985,
    detectedAt: '2026-09-01 18:42:10',
    zone: 'Zone 4 - High Tension Span',
    lengthMm: 420,
    depthMm: 14.8,
    status: 'ACTIVE',
  },
  {
    id: 'DM-089',
    type: 'LONGITUDINAL_TEAR',
    label: 'Chute Drop Longitudinal Slit',
    locationMeter: 1485,
    severity: 'WARNING',
    confidence: 0.942,
    detectedAt: '2026-09-01 17:15:33',
    zone: 'Zone 3 - Primary Feeder Impact',
    lengthMm: 185,
    depthMm: 7.2,
    status: 'ACTIVE',
  },
  {
    id: 'DM-062',
    type: 'SURFACE_GOUGE',
    label: 'Trapped Iron Ore Lump Gouge',
    locationMeter: 3120,
    severity: 'ADVISORY',
    confidence: 0.897,
    detectedAt: '2026-09-01 14:08:45',
    zone: 'Zone 5 - Overland Return Midpoint',
    lengthMm: 95,
    depthMm: 4.6,
    status: 'ACKNOWLEDGED',
  },
  {
    id: 'DM-041',
    type: 'EDGE_FRAY_DELAMINATION',
    label: 'Idler Misalignment Edge Fray',
    locationMeter: 3840,
    severity: 'ADVISORY',
    confidence: 0.915,
    detectedAt: '2026-09-01 10:24:19',
    zone: 'Zone 6 - Take-up Transition',
    lengthMm: 310,
    depthMm: 3.1,
    status: 'ACKNOWLEDGED',
  },
];

export const INITIAL_SENSOR_NODES: SensorNode[] = [
  {
    nodeId: 'ESP-01',
    name: 'Head Pulley Drive Station',
    location: 'Chainage 0+050m',
    type: 'LoRa_SX1278',
    status: 'ONLINE',
    batteryVoltage: 4.12,
    batteryPercent: 96,
    rssi: -62,
    snr: 10.2,
    packetLossPercent: 0.0,
    temperature: 42.1,
    vibrationRms: 2.8,
    frequencyPeakHz: 48.5,
    lastTelemetryTime: 'Just now',
  },
  {
    nodeId: 'CAM-01',
    name: 'Top Belt High-Speed Vision Scanner',
    location: 'Chainage 0+180m',
    type: 'HighSpeed_Vision',
    status: 'ONLINE',
    batteryVoltage: 12.4,
    batteryPercent: 100,
    rssi: -48,
    snr: 14.0,
    packetLossPercent: 0.0,
    temperature: 36.5,
    vibrationRms: 1.1,
    frequencyPeakHz: 120.0,
    lastTelemetryTime: 'Just now',
  },
  {
    nodeId: 'MFL-01',
    name: 'Magnetic & Ultrasonic Cord Scanner',
    location: 'Chainage 0+220m',
    type: 'Ultrasonic_MFL',
    status: 'ONLINE',
    batteryVoltage: 12.1,
    batteryPercent: 100,
    rssi: -52,
    snr: 12.8,
    packetLossPercent: 0.0,
    temperature: 37.8,
    vibrationRms: 1.4,
    frequencyPeakHz: 250.0,
    lastTelemetryTime: 'Just now',
  },
  {
    nodeId: 'ESP-04',
    name: 'Splice #4 Stress Monitor Node',
    location: 'Chainage 2+180m',
    type: 'Strain_Gauge_Array',
    status: 'ONLINE',
    batteryVoltage: 3.88,
    batteryPercent: 88,
    rssi: -74,
    snr: 8.9,
    packetLossPercent: 0.2,
    temperature: 58.2,
    vibrationRms: 6.9,
    frequencyPeakHz: 64.2,
    lastTelemetryTime: 'Just now',
  },
  {
    nodeId: 'ESP-07',
    name: 'Gravity Take-up Tower Node',
    location: 'Chainage 3+600m',
    type: 'LoRa_SX1278',
    status: 'ONLINE',
    batteryVoltage: 3.94,
    batteryPercent: 91,
    rssi: -82,
    snr: 7.1,
    packetLossPercent: 0.5,
    temperature: 41.3,
    vibrationRms: 4.1,
    frequencyPeakHz: 32.0,
    lastTelemetryTime: '1s ago',
  },
  {
    nodeId: 'ESP-12',
    name: 'Tail Pulley Reversal Station',
    location: 'Chainage 4+750m',
    type: 'LoRa_SX1278',
    status: 'ONLINE',
    batteryVoltage: 4.05,
    batteryPercent: 94,
    rssi: -79,
    snr: 7.8,
    packetLossPercent: 0.1,
    temperature: 35.6,
    vibrationRms: 2.3,
    frequencyPeakHz: 28.4,
    lastTelemetryTime: 'Just now',
  },
];

export const INITIAL_ALERTS: AlertLog[] = [
  {
    id: 'ALT-9042',
    timestamp: '2026-09-01 18:42:15',
    severity: 'CRITICAL',
    category: 'MECHANICAL',
    priority: 'P1_EMERGENCY',
    damageType: 'STEEL_CORD_PULL_OUT',
    title: 'IMMINENT JOINT RUPTURE RISK: Splice #4',
    description: 'Steel cord displacement exceeded 14.8mm safe threshold (limit: 12.0mm). Dynamic strain surge at 1280 uE with acoustic emission burst.',
    locationMeter: 2180,
    spliceId: 4,
    sensorId: 'ESP-04 / MFL-01',
    acknowledged: false,
    requiresInterlock: true,
    responseSlaSeconds: 45,
    playbookSteps: [
      { step: 1, title: 'Trigger 15s soft deceleration ramp', actionType: 'AUTO', completed: false },
      { step: 2, title: 'Verify gravity take-up counterweight brake lock', actionType: 'VERIFY', completed: false },
      { step: 3, title: 'Dispatch Mechanical Re-splice Crew Alpha', actionType: 'MANUAL', completed: false },
    ],
  },
  {
    id: 'ALT-CYBER-01',
    timestamp: '2026-09-01 18:05:22',
    severity: 'WARNING',
    category: 'CYBER_SECURITY',
    priority: 'P2_URGENT',
    damageType: 'CYBER_MODBUS_TAMPER',
    title: 'Modbus DPI: Unauthorized VFD Speed Override Attempt',
    description: 'Rogue IP 192.168.4.195 attempted unauthorized write to Holding Register 40012 (Target Speed = 7.5 m/s). DPI firewall dropped packet.',
    locationMeter: 50,
    sensorId: 'OT-FW-HEAD',
    acknowledged: false,
    requiresInterlock: false,
    responseSlaSeconds: 120,
    playbookSteps: [
      { step: 1, title: 'Block source MAC & IP on Level 2 switch', actionType: 'AUTO', completed: true },
      { step: 2, title: 'Rotate VFD PLC cryptographic Modbus session tokens', actionType: 'MANUAL', completed: false },
      { step: 3, title: 'Notify Site Industrial Cybersecurity Incident Lead', actionType: 'MANUAL', completed: false },
    ],
  },
  {
    id: 'ALT-SAFETY-01',
    timestamp: '2026-09-01 17:48:10',
    severity: 'WARNING',
    category: 'PHYSICAL_SAFETY',
    priority: 'P2_URGENT',
    damageType: 'PERIMETER_RED_ZONE_BREACH',
    title: 'Perimeter Safety Breach: Technician in Red Exclusion Zone',
    description: 'AI vision and RFID beacon detected worker within 1.2m of Head Drive Pulley nip-point without active LOTO zero-energy clearance.',
    locationMeter: 45,
    sensorId: 'CAM-01 / RFID-02',
    acknowledged: true,
    requiresInterlock: false,
    responseSlaSeconds: 30,
    playbookSteps: [
      { step: 1, title: 'Sound local audio warning horn in Zone 1', actionType: 'AUTO', completed: true },
      { step: 2, title: 'Verify technician cleared hazardous nip-point', actionType: 'VERIFY', completed: true },
      { step: 3, title: 'Log safety near-miss report into EHS portal', actionType: 'MANUAL', completed: true },
    ],
    actionTaken: 'Technician cleared perimeter immediately upon local warning tone.',
  },
  {
    id: 'ALT-8991',
    timestamp: '2026-09-01 17:15:40',
    severity: 'WARNING',
    category: 'MECHANICAL',
    priority: 'P3_HIGH',
    damageType: 'LONGITUDINAL_TEAR',
    title: 'Longitudinal Rip Detected (185mm) at Chute 1',
    description: 'Line-scan vision model detected sharp ore rock puncture downstream of primary transfer chute.',
    locationMeter: 1485,
    sensorId: 'CAM-01',
    acknowledged: true,
    requiresInterlock: false,
    actionTaken: 'Camera visual confirmation logged. Maintenance notified for shift change inspection.',
  },
  {
    id: 'ALT-8834',
    timestamp: '2026-09-01 14:09:00',
    severity: 'ADVISORY',
    category: 'MECHANICAL',
    priority: 'P4_DIAGNOSTIC',
    damageType: 'SURFACE_GOUGE',
    title: 'Surface Gouge on Return Run',
    description: 'Depth 4.6mm top rubber gouge detected. Below safety limit of 8.0mm.',
    locationMeter: 3120,
    sensorId: 'CAM-01',
    acknowledged: true,
    requiresInterlock: false,
  },
];

export function generateHistoricalStrainData(): MLMetrics['historicalStrainSeries'] {
  const points = [];
  const now = Date.now();
  for (let i = 24; i >= 0; i--) {
    const t = new Date(now - i * 60 * 1000);
    const timeStr = `${t.getHours().toString().padStart(2, '0')}:${t.getMinutes().toString().padStart(2, '0')}`;
    const base = 650 + Math.sin(i * 0.4) * 40;
    const noise = (Math.random() - 0.5) * 30;
    const actual = i < 4 ? base + 420 + Math.random() * 80 : base + noise;
    points.push({
      time: timeStr,
      actual: Math.round(actual),
      upperEnvelope: 1150,
      baseline: 650,
    });
  }
  return points;
}

export function generateVibrationTrendData(): MLMetrics['vibrationTrendSeries'] {
  const points = [];
  const now = Date.now();
  for (let i = 24; i >= 0; i--) {
    const t = new Date(now - i * 60 * 1000);
    const timeStr = `${t.getHours().toString().padStart(2, '0')}:${t.getMinutes().toString().padStart(2, '0')}`;
    points.push({
      time: timeStr,
      driveMotor: Number((2.8 + Math.sin(i * 0.3) * 0.4 + (Math.random() - 0.5) * 0.2).toFixed(2)),
      headPulley: Number((1.9 + Math.cos(i * 0.2) * 0.3 + (Math.random() - 0.5) * 0.15).toFixed(2)),
      tailPulley: Number((2.2 + (Math.random() - 0.5) * 0.3).toFixed(2)),
    });
  }
  return points;
}

export const INITIAL_ML_METRICS: MLMetrics = {
  isolationForestAnomalyScore: 0.88,
  rulHoursRemaining: 18.5,
  rulConfidenceInterval: [14.0, 24.0],
  falsePositiveRejectionRate: 99.4,
  modelInferenceLatencyMs: 8.4,
  modelVersion: 'v4.2-Edge-Quantized-ESP32',
  overallHealthScore: 71.4,
  historicalStrainSeries: generateHistoricalStrainData(),
  vibrationTrendSeries: generateVibrationTrendData(),
  damageDistribution: {
    longitudinalTears: 2,
    surfaceGouges: 7,
    spliceSlippage: 1,
    edgeWear: 4,
    foreignObjects: 0,
  },
};

export const INITIAL_TELEMETRY: ConveyorTelemetry = {
  isRunning: true,
  speedMps: 4.8,
  speedRpm: 624,
  tonnageTph: 8450,
  totalBeltLengthMeters: 4800,
  headDrivePowerKw: 1850,
  tailTensionKn: 410,
  ambientTempC: 36.5,
  shiftOperator: 'Capt. R. Deshmukh (Zone A Lead)',
  activeSector: 'Pilbara Pit #4 - Primary Overland Conveyor CV-204',
  interlockActive: false,
  interlockReason: null,
  decelerationRampActive: false,
};

export const INITIAL_PURDUE_ZONES: PurdueZoneStatus[] = [
  {
    level: 0,
    name: 'Level 0: Field Process Bus',
    description: 'Strain gauges, ultrasonic cord MFL sensors, and LoRa SX1278 telemetry endpoints.',
    status: 'SECURE',
    activeFirewallRules: 24,
    inspectedPackets: 284010,
    blockedAnomalies: 4,
  },
  {
    level: 1,
    name: 'Level 1: Basic Control & Safety PLCs',
    description: 'Rockwell GuardLogix SIL-3 Dual-Channel Emergency Trip Relays & VFD Drive Controllers.',
    status: 'SECURE',
    activeFirewallRules: 32,
    inspectedPackets: 195400,
    blockedAnomalies: 1,
  },
  {
    level: 2,
    name: 'Level 2: Supervisory SCADA LAN',
    description: 'Modbus TCP Deep Packet Inspection (DPI) & Holding Register Mutation Firewall.',
    status: 'ELEVATED',
    activeFirewallRules: 48,
    inspectedPackets: 512900,
    blockedAnomalies: 12,
  },
  {
    level: 3,
    name: 'Level 3: Site Operations DMZ',
    description: 'Industrial SIEM, mTLS API Gateway, Zero-Trust RBAC, and SAP PM Asset Connector.',
    status: 'SECURE',
    activeFirewallRules: 64,
    inspectedPackets: 891200,
    blockedAnomalies: 28,
  },
];

export const INITIAL_CYBER_THREATS: CyberThreatEvent[] = [
  {
    id: 'THR-701',
    timestamp: '18:05:22',
    threatType: 'MODBUS_INJECTION',
    sourceIpOrMac: '192.168.4.195 (Unauthorized Laptop)',
    targetDevice: 'VFD-DRIVE-01 [Reg 40012]',
    status: 'BLOCKED',
    severity: 'WARNING',
    details: 'Attempted to force conveyor speed from 4.8 m/s to 7.5 m/s exceeding mechanical rating.',
  },
  {
    id: 'THR-684',
    timestamp: '15:22:10',
    threatType: 'LORA_REPLAY',
    sourceIpOrMac: 'RF: 0x4B 0x88 (Unknown Transceiver)',
    targetDevice: 'Gateway-ESP-04',
    status: 'QUARANTINED',
    severity: 'WARNING',
    details: 'Replay of old telemetry packet hash detected. Nonce sequence validation rejected frame.',
  },
  {
    id: 'THR-640',
    timestamp: '11:14:05',
    threatType: 'MITM_PROBE',
    sourceIpOrMac: '10.24.1.80 (VLAN 4 Scanning)',
    targetDevice: 'SCADA HMI Server',
    status: 'BLOCKED',
    severity: 'ADVISORY',
    details: 'Port 502 (Modbus TCP) automated port scan detected and dropped by OT stateful firewall.',
  },
];

export const INITIAL_PERSONNEL: PersonnelZoneTracker[] = [
  {
    id: 'PER-01',
    name: 'Marcus Vance',
    rfidTag: 'RFID-9401',
    role: 'Lead Mechanical Technician',
    currentZone: 'Zone 1: Head Pulley Drive Walkway',
    inExclusionZone: false,
    lotoAuthorized: true,
    safetyDistanceM: 3.4,
  },
  {
    id: 'PER-02',
    name: 'Elena Rostova',
    rfidTag: 'RFID-8814',
    role: 'Electrical & Instrumentation Tech',
    currentZone: 'Zone 4: Mid-Span Gallery',
    inExclusionZone: false,
    lotoAuthorized: false,
    safetyDistanceM: 12.0,
  },
  {
    id: 'PER-03',
    name: 'Jacob M.',
    rfidTag: 'RFID-7712',
    role: 'Third-Party Contractor',
    currentZone: 'Zone 3: Transfer Feeder',
    inExclusionZone: false,
    lotoAuthorized: false,
    safetyDistanceM: 6.8,
  },
];

export const INITIAL_LOTO_LOCKS: LotoLockRecord[] = [
  {
    lockId: 'LOTO-401',
    pointName: '4160V Primary Drive Breaker (CB-01)',
    appliedBy: 'Marcus Vance (Cert #MV-881)',
    timestamp: '2026-09-01 06:30',
    status: 'RELEASED',
    keyHash: '0x8FA2...C19B',
  },
  {
    lockId: 'LOTO-402',
    pointName: 'Hydraulic Gravity Winch Take-up Isolator',
    appliedBy: 'Marcus Vance (Cert #MV-881)',
    timestamp: '2026-09-01 06:35',
    status: 'RELEASED',
    keyHash: '0x3D11...E4A0',
  },
];
